import Head from 'next/head'
import Image from 'next/image'
import { Container, Col, Row } from 'react-bootstrap'
import styles from '../styles/Home.module.css' 
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <Container >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <main className={styles.main}>

        <div  className={styles.header}>
          <p className={styles.title} >
          HACKER NEWS
          </p>
        </div> 

        <p> 
          <button className={styles.button}> <a href='#' >All</a></button>
          <button className={styles.button}> <a href='#'> My Faves </a></button>
        </p>
        
        <div>
        <select className={styles.select}>
          <option>
            alfa
          </option>
          <option>
            beta
          </option>
        </select>
        </div> 
  <Container className={styles.cont} >
    <Row className={styles.rowX}>
      <Col md={5} sm={8}  className={styles.cols}>
        <div >
          elemento
        </div>
         </Col>
      <Col md={5} sm={8} className={styles.cols}>
        <div >
          elemento
        </div>

      </Col>
      <Col md={5} sm={8} className={styles.cols}>
        <div>
          elemento
        </div>

      </Col>
      <Col md={5} sm={8} className={styles.cols}>
        <div>
          elemento 
        </div>
      </Col>
      <Col md={5} sm={8} className={styles.cols}>
        <div >
          elemento
        </div>
         </Col>
      <Col md={5} sm={8} className={styles.cols}>
        <div >
          elemento
        </div>

      </Col>
      <Col md={5} sm={8} className={styles.cols}>
        <div>
          elemento
        </div>

      </Col>
      <Col md={5} sm={8} className={styles.cols}>
        <div>
          elemento 
        </div>
      </Col>
    </Row>
  </Container>


      <div className={styles.pagi}>
        paginator
      </div> 
      </main>
 
    </Container>
  )
}
